version: '3.8'

services:
  teleserver:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: teleserver
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
