[workspace]
members = [
    "lib",
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
alloy-primitives = "0.7.7"
